// GENERATED by scripts/brand.py from brand.json — do not edit.
// The kit's brand words, from brand.json. Import them; never type them.
//   import { CLI, env, envName, cmd } from "./brand.ts"
//   env("PATH")         process.env[ENV_PREFIX + "PATH"] ?? fallback
//   envName("PATH")     ENV_PREFIX + "PATH"
//   cmd("memory new")   `${CLI} memory new`

export const DISPLAY_NAME = "agentic kit" // the kit's name in prose
export const CLI = "ak" // the command a person types
export const MARKETPLACE = "ak" // the plugin marketplace: ids are <plugin>@<marketplace>
export const ENV_PREFIX = "AK_" // prefix of every environment variable: env('PATH') reads <prefix>PATH
export const HOME_DIR = ".ak" // the dot-folder: ~/<home_dir> is the global home, <repo>/<home_dir> a scope
export const REPO_DIR = "agentic-kit" // the default checkout folder under $HOME: ~/<repo_dir>
export const WORKTREES_DIR = "agentic-kit-wt" // the default worktrees folder under $HOME: ~/<worktrees_dir>
export const GATEWAY_LABEL = "com.ak.gateway" // the gateway's launchd label
export const GATEWAY_CONFIG = "ak/gateway.json" // the gateway's config file, relative to ~/.config
export const GATEWAY_ACCOUNTS = "ak/accounts.json" // the gateway's accounts file, relative to ~/.config
export const GATEWAY_DATA = "ak/gateway" // the gateway's data folder, relative to ~/.local/share
export const RELEASE_DIR = "ak/release" // the release clone, relative to ~/.local/share

export function env(name: string): string | undefined
export function env(name: string, fallback: string): string
export function env(name: string, fallback?: string): string | undefined {
  return process.env[ENV_PREFIX + name] ?? fallback
}

export function envName(name: string): string {
  return ENV_PREFIX + name
}

export function cmd(verb = ""): string {
  return `${CLI} ${verb}`.trim()
}

// ---- the platform seam: paths, processes and locks that differ per OS. Node built-ins only. ----
// Rule: no component types ~/.claude, ~/.config, "/" or ":". It asks these instead.
// Source of this block: scripts/seam/platform.ts (edit there, then `scripts/brand.py render`).
import { spawn, type ChildProcess, type SpawnOptions } from "node:child_process"
import { homedir, tmpdir } from "node:os"
import { isAbsolute, join } from "node:path"

export const isWindows = (): boolean => process.platform === "win32"
export const isMacos = (): boolean => process.platform === "darwin"

function envPath(name: string): string | undefined {
  const v = process.env[name]
  if (!v) return undefined
  return v === "~" || v.startsWith("~/") || v.startsWith("~\\") ? join(homedir(), v.slice(1)) : v
}

function xdg(name: string): string | undefined {
  const v = process.env[name] // the XDG spec: a relative value is ignored
  return v && isAbsolute(v) ? v : undefined
}

/** Claude Code's config folder: $CLAUDE_CONFIG_DIR, else ~/.claude. */
export function claudeHome(): string {
  return envPath("CLAUDE_CONFIG_DIR") ?? join(homedir(), ".claude")
}

/** Claude Code's global state file: <CLAUDE_CONFIG_DIR>/.claude.json, else ~/.claude.json. */
export function claudeJson(): string {
  const d = envPath("CLAUDE_CONFIG_DIR")
  return d ? join(d, ".claude.json") : join(homedir(), ".claude.json")
}

/** Where config lives: %APPDATA% on Windows, else $XDG_CONFIG_HOME or ~/.config (macOS too). */
export function configDir(): string {
  if (isWindows()) return envPath("APPDATA") ?? join(homedir(), "AppData", "Roaming")
  return xdg("XDG_CONFIG_HOME") ?? join(homedir(), ".config")
}

/** Where data lives: %LOCALAPPDATA% on Windows, else $XDG_DATA_HOME or ~/.local/share. */
export function dataDir(): string {
  if (isWindows()) return envPath("LOCALAPPDATA") ?? join(homedir(), "AppData", "Local")
  return xdg("XDG_DATA_HOME") ?? join(homedir(), ".local", "share")
}

/** Where logs and state live: %LOCALAPPDATA% on Windows, else $XDG_STATE_HOME or ~/.local/state. */
export function stateDir(): string {
  if (isWindows()) return envPath("LOCALAPPDATA") ?? join(homedir(), "AppData", "Local")
  return xdg("XDG_STATE_HOME") ?? join(homedir(), ".local", "state")
}

export function tempDir(): string {
  return tmpdir()
}

/** A path with "/" separators, for matching and display. Use it before endsWith/split/includes. */
export function posix(p: string): string {
  if (isWindows()) {
    // Git Bash (Claude Code's Bash tool and hook shell) spells C:\x as /c/x (MSYS) or /cygdrive/c/x
    const m = /^(?:\/cygdrive)?\/([A-Za-z])(?=\/|$)/.exec(p)
    if (m) p = m[1].toUpperCase() + ":" + p.slice(m[0].length)
    return p.replace(/\\/g, "/")
  }
  return /^[A-Za-z]:[\\/]/.test(p) ? p.replace(/\\/g, "/") : p
}

/** The folder name Claude Code gives a working directory under <claudeHome>/projects: every character
 *  but a-z A-Z 0-9 becomes "-". It cannot be reversed, so prefer the cwd or transcript_path a payload
 *  carries over deriving one from the other. */
export function slug(cwd: string): string {
  return cwd.replace(/[^a-zA-Z0-9]/g, "-")
}

export function projectDir(cwd: string): string {
  return join(claudeHome(), "projects", slug(cwd))
}

/** True when the process exists (signal 0 only probes; Node's Windows build does the same). */
export function pidAlive(pid: number): boolean {
  if (!Number.isInteger(pid) || pid <= 0) return false
  try {
    process.kill(pid, 0)
    return true
  } catch (e) {
    return (e as NodeJS.ErrnoException).code === "EPERM"
  }
}

/** Start a process that outlives the caller, with no console window. */
export function spawnDetached(command: string, args: string[] = [], opts: SpawnOptions = {}): ChildProcess {
  const child = spawn(command, args, { stdio: "ignore", ...opts, detached: true, windowsHide: true })
  child.unref()
  return child
}
