# GENERATED by scripts/brand.py from brand.json — do not edit.
"""The kit's brand words, from brand.json. Import them; never type them.

    from _brand import CLI, env, env_name, cmd     # a hook or a script: the file beside it
    from ._brand import CLI, env, env_name, cmd    # a module inside a src package

    env("PATH")        os.environ.get(ENV_PREFIX + "PATH", default)
    env_name("PATH")   ENV_PREFIX + "PATH"  (monkeypatch.setenv, subprocess env=, text)
    cmd("memory new")  f"{CLI} memory new"
"""
import os

DISPLAY_NAME = "agentic kit"  # the kit's name in prose
CLI = "ak"  # the command a person types
MARKETPLACE = "ak"  # the plugin marketplace: ids are <plugin>@<marketplace>
ENV_PREFIX = "AK_"  # prefix of every environment variable: env('PATH') reads <prefix>PATH
HOME_DIR = ".ak"  # the dot-folder: ~/<home_dir> is the global home, <repo>/<home_dir> a scope
REPO_DIR = "agentic-kit"  # the default checkout folder under $HOME: ~/<repo_dir>
WORKTREES_DIR = "agentic-kit-wt"  # the default worktrees folder under $HOME: ~/<worktrees_dir>
GATEWAY_LABEL = "com.ak.gateway"  # the gateway's launchd label
GATEWAY_CONFIG = "ak/gateway.json"  # the gateway's config file, relative to ~/.config
GATEWAY_ACCOUNTS = "ak/accounts.json"  # the gateway's accounts file, relative to ~/.config
GATEWAY_DATA = "ak/gateway"  # the gateway's data folder, relative to ~/.local/share
RELEASE_DIR = "ak/release"  # the release clone, relative to ~/.local/share


def env(name, default=None):
    return os.environ.get(ENV_PREFIX + name, default)


def env_name(name):
    return ENV_PREFIX + name


def cmd(verb=""):
    return f"{CLI} {verb}".strip()


# ---- the platform seam: paths, processes and locks that differ per OS. Stdlib only. ----
# Rule: no component types ~/.claude, ~/.config, "/", ":" or fcntl. It asks these instead.
# Source of this block: scripts/seam/platform.py (edit there, then `scripts/brand.py render`).
import os
import sys


def _path(*parts):
    from pathlib import Path  # lazy: pathlib costs ~4.5 ms and hooks import this file on every call
    return Path(*parts)


def _home():
    return _path(os.path.expanduser("~"))


def is_windows():
    return sys.platform == "win32"


def is_macos():
    return sys.platform == "darwin"


def _env_path(name):
    v = os.environ.get(name)
    return _path(v).expanduser() if v else None


def _xdg(name):
    v = os.environ.get(name)  # the XDG spec: a relative value is ignored
    return _path(v) if v and os.path.isabs(v) else None


def claude_home():
    """Claude Code's config folder: $CLAUDE_CONFIG_DIR, else ~/.claude."""
    return _env_path("CLAUDE_CONFIG_DIR") or _home() / ".claude"


def claude_json():
    """Claude Code's global state file: <CLAUDE_CONFIG_DIR>/.claude.json, else ~/.claude.json."""
    d = _env_path("CLAUDE_CONFIG_DIR")
    return d / ".claude.json" if d else _home() / ".claude.json"


def config_dir():
    """Where config lives: %APPDATA% on Windows, else $XDG_CONFIG_HOME or ~/.config (macOS too)."""
    if is_windows():
        return _env_path("APPDATA") or _home() / "AppData" / "Roaming"
    return _xdg("XDG_CONFIG_HOME") or _home() / ".config"


def data_dir():
    """Where data lives: %LOCALAPPDATA% on Windows, else $XDG_DATA_HOME or ~/.local/share."""
    if is_windows():
        return _env_path("LOCALAPPDATA") or _home() / "AppData" / "Local"
    return _xdg("XDG_DATA_HOME") or _home() / ".local" / "share"


def state_dir():
    """Where logs and state live: %LOCALAPPDATA% on Windows, else $XDG_STATE_HOME or ~/.local/state."""
    if is_windows():
        return _env_path("LOCALAPPDATA") or _home() / "AppData" / "Local"
    return _xdg("XDG_STATE_HOME") or _home() / ".local" / "state"


def temp_dir():
    import tempfile
    return _path(tempfile.gettempdir())


def posix(p):
    """A path as a string with "/" separators, for matching and display. Use it before endswith/split/in."""
    import re
    s = str(p)
    if is_windows():
        # Git Bash (what Claude Code's Bash tool and hook shell use) spells C:\x as /c/x (MSYS) or /cygdrive/c/x
        m = re.match(r"^(?:/cygdrive)?/([A-Za-z])(?=/|$)", s)
        if m:
            s = m.group(1).upper() + ":" + s[m.end():]
        return s.replace("\\", "/")
    if re.match(r"^[A-Za-z]:[\\/]", s):
        return s.replace("\\", "/")
    return s


def slug(cwd):
    """The folder name Claude Code gives a working directory under <claude_home>/projects:
    every character but a-z A-Z 0-9 becomes "-" (one per UTF-16 unit, as JavaScript counts).
    It cannot be reversed (a "-" may have been "/", ".", " " or "-"), so prefer the cwd or
    transcript_path a hook payload carries over deriving one from the other."""
    return "".join(c if (c.isascii() and c.isalnum()) else ("--" if ord(c) > 0xFFFF else "-") for c in str(cwd))


def project_dir(cwd):
    return claude_home() / "projects" / slug(cwd)


def pid_alive(pid):
    """True when the process exists. Never signals it: os.kill(pid, 0) TERMINATES the process on Windows."""
    pid = int(pid)
    if pid <= 0:
        return False
    if is_windows():
        import ctypes
        k32 = ctypes.WinDLL("kernel32", use_last_error=True)
        k32.OpenProcess.restype = ctypes.c_void_p
        k32.GetExitCodeProcess.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_ulong)]
        k32.CloseHandle.argtypes = [ctypes.c_void_p]
        h = k32.OpenProcess(0x1000, False, pid)  # PROCESS_QUERY_LIMITED_INFORMATION
        if not h:
            return ctypes.get_last_error() == 5  # ERROR_ACCESS_DENIED: it exists, it is not ours
        try:
            code = ctypes.c_ulong()
            return bool(k32.GetExitCodeProcess(h, ctypes.byref(code))) and code.value == 259  # STILL_ACTIVE
        finally:
            k32.CloseHandle(h)
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True


def lock_file(fh, blocking=True):
    """Take an exclusive advisory lock on an open file (flock; msvcrt on Windows). BlockingIOError when
    not blocking and it is held. Closing the file releases it."""
    if is_windows():
        import msvcrt
        import time
        fh.seek(0)
        while True:
            try:
                msvcrt.locking(fh.fileno(), msvcrt.LK_NBLCK, 1)
                return
            except OSError:
                if not blocking:
                    raise BlockingIOError("locked")
                time.sleep(0.05)
    import fcntl
    fcntl.flock(fh, fcntl.LOCK_EX | (0 if blocking else fcntl.LOCK_NB))


def unlock_file(fh):
    if is_windows():
        import msvcrt
        fh.seek(0)
        msvcrt.locking(fh.fileno(), msvcrt.LK_UNLCK, 1)
        return
    import fcntl
    fcntl.flock(fh, fcntl.LOCK_UN)


class lock:
    """with lock(path): ...  an exclusive advisory lock on `path` (created, with its folder, if missing)."""

    def __init__(self, path, blocking=True):
        self.path, self.blocking, self.fh = _path(path), blocking, None

    def __enter__(self):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.fh = open(self.path, "a+b")
        try:
            lock_file(self.fh, self.blocking)
        except BaseException:
            self.fh.close()
            raise
        return self.fh

    def __exit__(self, *exc):
        try:
            unlock_file(self.fh)
        finally:
            self.fh.close()


def spawn_detached(argv, **kw):
    """Start a process that outlives the caller, with no console window. Returns the Popen."""
    import subprocess
    for k in ("stdin", "stdout", "stderr"):
        kw.setdefault(k, subprocess.DEVNULL)
    if is_windows():
        # CREATE_NO_WINDOW | CREATE_NEW_PROCESS_GROUP. Not DETACHED_PROCESS: that leaves the child with no
        # console at all, so every console program it starts (git, claude, uv) opens a visible window.
        kw["creationflags"] = kw.get("creationflags", 0) | 0x08000000 | 0x00000200
    else:
        kw.setdefault("start_new_session", True)
    return subprocess.Popen(argv, **kw)


def which_exe(name):
    """Like shutil.which, but on Windows prefers a real .exe/.com over a .cmd/.bat shim: a shim cannot be
    spawned without a shell, and cmd.exe cuts an argument at its first newline. None when not found."""
    import shutil
    if is_windows() and not os.path.splitext(name)[1]:
        for ext in (".exe", ".com"):
            hit = shutil.which(name + ext)
            if hit:
                return hit
    return shutil.which(name)


def replace_retry(src, dst, tries=6):
    """os.replace that rides out Windows' PermissionError while a reader still has `dst` open."""
    import time
    for i in range(tries):
        try:
            return os.replace(src, dst)
        except PermissionError:
            if not is_windows() or i == tries - 1:
                raise
            time.sleep(0.05)


def utf8_stdio():
    """Make stdin, stdout and stderr UTF-8 whatever the console's code page (Windows defaults to cp1252)."""
    for s in (sys.stdin, sys.stdout, sys.stderr):
        try:
            s.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
